version: "3.7"

services:
  #THIS IS THE NAME OF THE SERVICE THAT SHOULD BE IN THE CONNECTION CREATION FILE
  database:
    image: postgres
    container_name: database_la_concierge_auth
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=laconcierge
      - POSTGRES_PASSWORD=laconcierge
      - POSTGRES_DB=la_concierge_auth
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: la_concierge_auth
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
      - /usr/app/node_modules/bcrypt/
    links:
      - database
    depends_on:
      - database

volumes:
  pgdata:
    driver: local
